workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    clerk-openapi:
        inputs:
            - location: https://raw.githubusercontent.com/clerk/openapi-specs/refs/heads/main/bapi/2024-10-01.yml
        overlays:
            - location: ./examples.yaml
            - location: https://raw.githubusercontent.com/clerk/openapi-specs/refs/heads/main/.speakeasy/bapi/fixes.yml
        registry:
            location: registry.speakeasyapi.dev/clerk/clerk/clerk-openapi
targets:
    clerk-sdk-python:
        target: python
        source: clerk-openapi
        output: .
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/clerk/clerk/clerk-openapi-python-code-samples
            blocking: false
